DROP DATABASE IF EXISTS tienda_virtual;

CREATE DATABASE tienda_virtual;

USE tienda_virtual;


-- Table: TRABAJADORES
CREATE TABLE TRABAJADORES (
    IDTRABAJADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Cargo VARCHAR(50) NOT NULL,
    Sueldo INT NOT NULL
);

-- Table: VENTAS
CREATE TABLE VENTAS(
	IDVENTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDTRABAJADOR INT NOT NULL,
    Fecha DATETIME,
    Monto INT NOT NULL
);

-- Table: PRODUCTOS
CREATE TABLE PRODUCTOS (
    IDPRODUCTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDCATEGORIA INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(100),
    Precio INT NOT NULL,
    Stock INT NOT NULL
);

-- Table: PROVEEDORES
CREATE TABLE PROVEEDORES (
    IDPROVEEDOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Contacto INT NOT NULL
);

-- Table: CATEGORIAS
CREATE TABLE CATEGORIAS (
    IDCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT NOT NULL,
    IDPROVEEDOR INT NOT NULL,
    Descripcion VARCHAR(100)
);

-- Table: CLIENTES
CREATE TABLE CLIENTES (
    IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL,
    Correo VARCHAR(30) UNIQUE NOT NULL,
    Telefono VARCHAR(30) DEFAULT 'Unknown',
    Direccion VARCHAR(255) NOT NULL,
    IDFACTURA INT NOT NULL
);

-- Table: FACTURAS
CREATE TABLE FACTURAS (
    IDFACTURA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDTRABAJADOR INT NOT NULL,
    IDVENTA INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    Total DECIMAL(10 , 2 ) NOT NULL
);


-- DEFINICION FOREIGN KEYS

-- Table: VENTAS
ALTER TABLE VENTAS
    ADD CONSTRAINT FK_VENTAS_TRABAJADORES
    FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADORES(IDTRABAJADOR);
    
-- Table: PRODUCTOS
ALTER TABLE PRODUCTOS
    ADD CONSTRAINT FK_PRODUCTOS_CATEGORIAS
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA);
    
-- Table: PROVEEDORES
ALTER TABLE PROVEEDORES
    ADD CONSTRAINT FK_PROVEEDORES_PRODUCTOS
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);

-- Table: CATEGORIAS
ALTER TABLE CATEGORIAS
    ADD CONSTRAINT FK_CATEGORIAS_PRODUCTOS
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);
    
    ALTER TABLE CATEGORIAS
    ADD CONSTRAINT FK_CATEGORIAS_PROVEEDORES
    FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES(IDPROVEEDOR);
    
-- Table: CLIENTES
ALTER TABLE CLIENTES
    ADD CONSTRAINT FK_CLIENTES_FACTURAS
    FOREIGN KEY (IDFACTURA) REFERENCES FACTURAS(IDFACTURA);
    
-- Table: FACTURAS

ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_TRABAJADOR
    FOREIGN KEY (IDTRABAJADOR) REFERENCES TRABAJADORES(IDTRABAJADOR);
    
ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_VENTAS
    FOREIGN KEY (IDVENTA) REFERENCES VENTAS(IDVENTA);
    
ALTER TABLE FACTURAS
    ADD CONSTRAINT FK_FACTURAS_PRODUCTOS
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);